### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by jantimon** [runk/connect-jade-static#10]
Hi, 

I am using the latest version of connect-jade-static ( 0.1.5 ).
Unfortunately it is now sending 404 errors.

My usecase is that I have multiple middlewares e.g.

```js
  var express = require('express');
  var app = express();
  app.use(jadeStatic({
    baseDir: publicDirectory,
    baseUrl: baseUrl
  }));
  app.use(express.static(publicDirectory));
```

The public folder contains three files:
* index.jade
* demo.html
* styles.css

As there is no valid template for styles.css connect-jade-static returns 404 although the styles.css file exists and the connect-jade-static middle ware is not responsible.
Same thing happens for demo.html

Could you please call next() if you can't find a tpl for the request url?
It would be in https://github.com/runk/connect-jade-static/blob/master/index.js#L27

**Comment by runk** [comment]
Hi @jantimon 

Sure, I think we can do it. **v0.1.6** is published.

**Comment by jantimon** [comment]
Just tested it - works like intended.
Thanks alot
